#!/bin/bash

DIR_CONFIG=${HOME}/.config/opencode
MODEL=${1}
if [[ -n "$MODEL" ]]; then
  MODEL="-$MODEL"
fi
CONFIG_IMPL=oh-my-opencode-kimi${MODEL}.json
CONFIG=oh-my-opencode.json

ln -sf ${DIR_CONFIG}/${CONFIG_IMPL} ${DIR_CONFIG}/${CONFIG}
opencode .
